### ISSUE TITLE
Should we actually check if the filtered data has changed before emitting the filterChanged event?

### ISSUE THREAD

**Issue by starikcetin** [Paraboly/pwc-filter#5]
Doing a proper check will have some minor performance hits.
Not doing so means we may emit a filterChanged event while the filtered data is exactly the same.

Related: https://github.com/Paraboly/pwc-dynamic-form/issues/7

**Comment by SchemeSonic** [comment]
<del>Well, it could be NP for most of the cases, i think we should postponed it. </del>

Hmm just a question, emitting with wrong data you mean right? If so, we should emit filtered data.

**Comment by starikcetin** [comment]
Not exactly. We filter the data before emitting the change event, so the result is always correct, and on par with the value you get via the manual filter method.

Currently, if the underlying dynamic form emits a change event, the filter also emits a change event. The issue is that, we emit the change event without performing a check to see if the old filter result and the new filter result are the same. So the user might get change events from the filter, but the filter result may be exactly the same as the previous one.

My question is just that: should we check for deep equality of the previous filter result and the new filter result before emitting the change event?

**Comment by starikcetin** [comment]
This is overengineering.
